# .github/workflows/heroku-deploy.yml

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  heroku-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Login to Heroku Container registry
        env: 
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: sudo apt update && sudo apt install heroku && heroku container:login
      #- name: Check out repository
      #  uses: actions/checkout@v2
      #- name: Deploy to Heroku
      #  uses: akhileshns/heroku-deploy@v3.12.12
      #  with:
      #    heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
      #    heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
      #    heroku_email: ${{ secrets.HEROKU_EMAIL }}
